version: "3"
services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
  db:
    image: postgres:16-alpine
    ports:
      - 5431:5432
    container_name: db
    env_file:
      - .env
    volumes:
      - pgData:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  pgData:
  redis_volume_data:
  redis_insight_volume_data:
